// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Qhw5SPCRTRCML3vuSxAdYGfKos5drVU',
    appId: '1:678016711135:web:94720e6f0a5e3e0ecd2c6a',
    messagingSenderId: '678016711135',
    projectId: 'smartwire-f275b',
    authDomain: 'smartwire-f275b.firebaseapp.com',
    storageBucket: 'smartwire-f275b.appspot.com',
    measurementId: 'G-ZK297DJNZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaup4djTfe2u9JbZ3Qao4ai7ZRG9W2pO0',
    appId: '1:678016711135:android:9993db4c4f967baccd2c6a',
    messagingSenderId: '678016711135',
    projectId: 'smartwire-f275b',
    storageBucket: 'smartwire-f275b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXf-6m6YokHscU8BBby1MNeV8g7pysxks',
    appId: '1:678016711135:ios:ec7f30fc085223a0cd2c6a',
    messagingSenderId: '678016711135',
    projectId: 'smartwire-f275b',
    storageBucket: 'smartwire-f275b.appspot.com',
    iosBundleId: 'com.example.smartwireMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXf-6m6YokHscU8BBby1MNeV8g7pysxks',
    appId: '1:678016711135:ios:ec7f30fc085223a0cd2c6a',
    messagingSenderId: '678016711135',
    projectId: 'smartwire-f275b',
    storageBucket: 'smartwire-f275b.appspot.com',
    iosBundleId: 'com.example.smartwireMobile',
  );
}
